<?php require 'structure/header.php'; ?>
<?php require 'structure/leftcolumn.php'; ?>
<?php require 'structure/content.php'; ?>
<!-- TEXTOS -->
<div>
    <!-- TEXTO 1 -->
    <div style="border-bottom:1px solid #f0f0f0;padding-top:16px;padding-bottom:16px;">
        <div style="overflow:hidden;margin-left:50px;margin-top:-5px;padding-right:25px;">
            <div>
                <h3>Weeks 3 & 4</h3>
                Hi All:<br><br>These past two weeks we have been exposed to both the concepts and practical applications of TVM. While I try to de-emphasize the role of calculations, it is only to make us focus on what is important -- the framework. But I strongly encourage you to use spreadsheets once you understand what is going on; and doing some problems without using the built-in formulae is actually quite useful.<br><br>As promised, I am releasing two weeks’ worth of material because it makes sense to do so. I review the last mega-example we did last week as part of the Week 2 Recap and then move on to new material.<br><br>Weeks 3 and 4 are all about decision-making criteria. This topic is extremely important, in my view. Value creation is not easy, but a surprisingly large fraction of us use decision criteria that are myopic and may actually be value-destructive. These two weeks will expose you to some of the fundamental reasons why some firms are repeatedly able to create value, while others do so for only short periods. Some of the calculations may seem easy and mechanical; but that is partly because these are simple extensions of what we have already learned. But understanding what the various widely used criteria really mean, and why some criteria are better than others, are the really important lessons here. And of course we again attempt to introduce everything with practical applications.<br><br>One final, but important, issue related to the next two weeks. In the second part of the fourth week, we will spend some time on the estimation of cash flows. This is an important component of project analysis, but requires an exposure to accounting. Since we do not have enough time to cover all the details, and the fact that accounting conventions vary across different countries, I focus on the most important cash flow estimation principles. I however strongly recommend that you take a class in accounting and/or learn it on your own if you want to know more about cash flow estimation. Accounting is the language of business and some exposure, beyond this class, will be helpful.<br><br>Also, although I do cover all the specifics in class, to help you execute some of the cash-flow based assignment questions, Taylor has prepared a really nice Sample Cash Flow Template that I have posted as a note. The note uses a fairly rich example to demonstrate the creation of a cash flow model. I think you will find it very useful to recreate the example in a spreadsheet using all the notes provided in the template.<br><br>I know that videos and assignments can get to be a lot of work. But if you stay focused on why you are doing specific things, it all will make sense. The beauty of finance is that it all fits together.<br><br><br>Gautam<br>                                                                </div>
        </div>
    </div>
    <!-- TEXTO 2 -->
    <div style="border-bottom:1px solid #f0f0f0;padding-top:16px;padding-bottom:16px;">
        <div style="overflow:hidden;margin-left:50px;margin-top:-5px;padding-right:25px;">
            <h3>Values</h3>
            <div>
                Hi All:<br><br>I want us to think about our values. There have been copyright infringements both on our forums and elsewhere. We have removed all the posts offering or requesting illegal copies of copyrighted materials from the forums of the class. You will be removed from the class if you indulge in such activity and reported to law enforcement. Please do not get involved in such activity elsewhere either.The law on this issue is pretty straightforward.<br><br>I however want to go beyond the law to our values. Everything begins and ends with values because they ultimately guide us when things become fuzzy; like most anything important in life. For example, you can and should collaborate on assignments, but you know when you are collaborating and when it is simply "cut and paste." Most, significantly, we all know that love is better than hate; it is not a law, yet the only value that makes us human. Everything else is detail.<br><br>So, be good, and respect yourself by making the right choices. Whenever we choose the right path, and we can always tell, life becomes suddenly uncomplicated and quite simple, really.<br><br><br>Gautam
            </div>
        </div>
    </div>
</div>
<?php require 'structure/footer.php'; ?>